Fixed missing hyphen issue in markdown-server line. py-gfm doesn't import properly. ImportError('Failed loading extension "mdx_gfm".') ImportError: cannot import name 'PartialGithubFlavoredMarkdownExtension' from partially initialized module 'mdx_partial_gfm' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/mdx_partial_gfm/__init__.py)